# Router Configuration
model:
  name: "router_model"
  architecture: "transformer"
  hidden_size: 768
  num_experts: 8
  top_k: 2

training:
  batch_size: 32
  learning_rate: 0.001
  epochs: 100
  save_steps: 1000
  
data:
  train_path: "data/training/router_data.json"
  val_path: "data/validation/router_data.json"
  
paths:
  model_save_path: "models/router/trained/"
  checkpoint_path: "models/router/checkpoints/"
